In [1]:
a = [1.0,2.0,1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [4]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1] # tensor(1.) 은 실수형 1.0을 나타낸 거임

tensor(1.)

In [6]:
float(a[1])

1.0

In [7]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [9]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [11]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [12]:
points[0]

tensor(4.)

In [13]:
points = torch.tensor([[4.0,1.0],[5.0,3],[2.,1.]]) 
# 톈서가 실수형일 경우 정수형 데이터 값을 넣어줘도 알아서 실수형으로 바꿔준다
# 하지만 텐서의 데이터 타입과 할당하려는 데이터 값의 타입이 호환이 되지 않을 경우 오류가 발생 할 수 있다
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [14]:
points.shape

torch.Size([3, 2])

In [15]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
print("0 번째 리스트의 1 번째 값",points[0,1])
print("1 번째 리스트의 1 번째 값",points[1,1])
print("2 번째 리스트의 0 번째 값",points[2,0])

0 번째 리스트의 1 번째 값 tensor(1.)
1 번째 리스트의 1 번째 값 tensor(3.)
2 번째 리스트의 0 번째 값 tensor(2.)


In [18]:
print("0번 째 리스트",points[0])

0번 째 리스트 tensor([4., 1.])


In [19]:
some_list = list(range(6))
print("리스트의 모든 요소",some_list[:])
print("리스트의 1번 부터 끝까지",some_list[1:])
print("리스트의 처음부터 4번 인덱스 전까지",some_list[:4])
print("리스트의 첫 번째 요소 부터 끝까지 ",some_list[:-1])
print("리스트의 1번 인덱스 요소부터 4번 인덱스 요소 전까지, 각 단계식 건너뛰면서",some_list[1:4:2])

리스트의 모든 요소 [0, 1, 2, 3, 4, 5]
리스트의 1번 부터 끝까지 [1, 2, 3, 4, 5]
리스트의 처음부터 4번 인덱스 전까지 [0, 1, 2, 3]
리스트의 첫 번째 요소 부터 끝까지  [0, 1, 2, 3, 4]
리스트의 1번 인덱스 요소부터 4번 인덱스 요소 전까지, 각 단계식 건너뛰면서 [1, 3]


In [20]:
print("points: \n", points)
print()
print("1 번째 이후 모든 행, 암묵적으로 모든 열이 포함\n",points[1:])
print()
print("1 번째 이후 모든 행, 명시적으로 모든 열이 포함\n",points[1:, :])
print()
print("1 번째 이후 모든 행에 대해 첫 번째 열이 포함\n",points[1:, 0])
print()
print("길이가 1인 차원 추가 \n",points[None])
points= points[None]
print(points.shape)

points: 
 tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

1 번째 이후 모든 행, 암묵적으로 모든 열이 포함
 tensor([[5., 3.],
        [2., 1.]])

1 번째 이후 모든 행, 명시적으로 모든 열이 포함
 tensor([[5., 3.],
        [2., 1.]])

1 번째 이후 모든 행에 대해 첫 번째 열이 포함
 tensor([5., 2.])

길이가 1인 차원 추가 
 tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])
torch.Size([1, 3, 2])
