In [2]:
import time # 파이썬의 기본 내장함수로 시간관련 라이브러리
import matplotlib.pyplot as plt # 시각화를 위환 라이브러리 
import numpy as np # 다양한 계산 ex)행렬과 같은 계산을 할 수 있게 해주는 라이브러리
import torch #pytorch 인공지능 및 딥러닝 모델을 구축하고 학습하기 위한 오픈 소스 딥러닝 라이브러리
import torch.nn as nn # neural network의 약자로, 신경망 모델을 구성하는 데 사용되는 다양한 레이어, 손실 함수, 초기화 함수등을 포함하는 라이브러리
import torch.utils.data as data # pytorch에서 데이터셋을 로드하고 전처리하는데 사용되는 유틸리티 함수와 클래스를 제공하는 함수
from matplotlib.colors import to_rgba # 그래프에 색깔 넣기 위한 도구
from torch import Tensor # 텐서를 많이 쓸것 같으니 그냥 클래스 하나를 따로 import함




In [3]:
print("Using torch", torch.__version__) # torch버전 확인 
#+cu117 ==cuda 11.7 과 호환되도록 빌드되었다.

Using torch 2.0.1+cu117


In [4]:
torch.manual_seed(42) 
# 시드를 설정하여 난수를 생성할 때 동일한 난수가 나오게 만듬
# 동일한 난수를 생성? -> 난수를 생성한다는게 무작위 수를 만든다는게 아니라 특정 알고리즘에 의해 어떠한 수를 생성하는거임 근데 시드42를 기반으로 알고리즘을 돌려준다고 하면 게속 같은 난수가 나오는거
# 시드? -> 난수 생성 과정에서 시작점을 지정하는 역할, 그냥 초기값이라 생각하면 됨
# 왜 이런짓을? -> 재현가능하게 만들어야 하는데 돌릴때마다 결과값이 달라지면 제대로 하고 있는지 헷갈려서

In [5]:
x =Tensor(2,3,4) # 3*4 행렬 2개 
print(x)

tensor([[[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 3.8990e-02,  4.5566e-41, -5.1625e-12,  6.0646e+13],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [-7.7060e-11,  4.5565e-41,  9.1084e-44,  0.0000e+00]]])


torch.Tensor는 pytorch에서 다차원 배열을 나타내는 클래스임
이 클래스를 이용하면 새로운 텐서를 생성할 때, 이미 메모리에 할당되어 있는 값을 재사용할 수 있음.
ex) a = 10
    b = a (a가 참조하는 값 10을 재사용)
이렇게 하면 메모리 절약 이득 && 귀찮게 다시 할당할 필요도 없음 :D


In [6]:
x1 = torch.zeros(1,2,3) # 0으로 가득찬 텐서
x2 = torch.ones(2,2,3) # 1로 가득찬 텐서
x3 = torch.rand(3,2,3) # 0과 1 사이에서 균일하게 샘플링된 임의의 값으로 채워진 텐서
x4 = torch.randn(4,2,3) # 평균이 0 이고 분산이 1인 정규 분포에서 샘플링된 임의의 값으로 체워진 텐서
x5 = torch.arange(3,7,2) # 정해진 규칙으로 텐서를 생성 (시작, 끝, 몇 칸씩 움직일 건지)
x6 = torch.Tensor(2,2,3) # 자기 멋대로 값을 채운 텐서 생성
# 샘플링? -> 통계학 또는 확률론에서 주어진 분포로부터 데이터 포인트를 추출하는 과정
# 데이터 포인트? - > 데이터 집합에서 개별적으로 측정된 하나의 관측값
for i in range(1,7):
    xi = eval('x' + str(i)) #eval()문자열을 그냥 코드로 보고 실행시킴, 보안상 안 좋으니 외부 입력이 있을 시 사용 하지 말 것!
    print('x{}\n{}'.format(i,xi))

x1
tensor([[[0., 0., 0.],
         [0., 0., 0.]]])
x2
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
x3
tensor([[[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]],

        [[0.2566, 0.7936, 0.9408],
         [0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739]]])
x4
tensor([[[-0.4974,  0.4396, -0.7581],
         [ 1.0783,  0.8008,  1.6806]],

        [[ 0.3559, -0.6866,  1.5736],
         [-0.8455,  1.3123,  0.6872]],

        [[-1.0892, -0.3553, -0.9138],
         [-0.6581,  0.0499,  2.2667]],

        [[ 1.1790, -0.4345, -1.3864],
         [-1.2862, -1.4032,  0.0360]]])
x5
tensor([3, 5])
x6
tensor([[[4.0436e-34, 0.0000e+00, 4.0555e-02],
         [4.5566e-41, 4.0438e-34, 0.0000e+00]],

        [[0.0000e+00, 7.0065e-45, 0.0000e+00],
         [0.0000e+00, 1.6605e-42, 0.0000e+00]]])


텐서란?
다차원 배열을 표현하기 위한 데이터 구조
벡터, 행렬, 같은 것들

In [7]:
x = Tensor([[1,2], [3,4]]) # 리스트 두개를 하나로 묶어서 텐서를 생성할 수 있다.
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [8]:
x = torch.rand(2,3,4)
shape = x.shape 
print("Shape:", x.shape)
print("Type:",type(shape))

size = x.size()
print("Size:", size)
print("Type:",type(size))
dim1, dim2, dim3 = x.size()

print("Size:", dim1, dim2, dim3)

# shape와 size 모두 텐서의 모양을 알려준다
# 옛날에는 몰라도 지금은 타입도 같고 출력 형태도 같음

Shape: torch.Size([2, 3, 4])
Type: <class 'torch.Size'>
Size: torch.Size([2, 3, 4])
Type: <class 'torch.Size'>
Size: 2 3 4


In [9]:
np_arr = np.array([[1,2], [3,4]]) 
tensor = torch.from_numpy(np_arr) # numpy를 tensor로 전환

print("Numpy array:", '\n', np_arr) 
print("PyTorch tensor:",'\n', tensor)
print(tensor.device) # 텐서가 gpu에 있는지 cpu에 있는지 출력

tensor = tensor.numpy() # 텐서를 numpy로 변환하기 위해서는 텐서가 cpu에 있어야 한다, ex) np_arr = tensor.cpu().numpy()
print("convert tnesor to numpy:", '\n', tensor)

Numpy array: 
 [[1 2]
 [3 4]]
PyTorch tensor: 
 tensor([[1, 2],
        [3, 4]])
cpu
convert tnesor to numpy: 
 [[1 2]
 [3 4]]


In [10]:
torch.manual_seed(42)  # x1,x2 각 텐서들의 원소들이 항상 같은 수들로 채워짐
x1 = torch.rand(2,3)
x2 = torch.rand(2,3)
y = x1 + x2 # 같은 위치에 있는 원소끼리 더함

print("x1", x1)
print()
print("x2", x2)
print()
print("y", y)

x1 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

x2 tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

y tensor([[1.1388, 1.7086, 1.3236],
        [1.0925, 1.3250, 1.1945]])


In [11]:
x1 = torch.rand(2,3)
x2 = torch.rand(2,3)

print("x1:", x1)
print("x2:", x2)
print()
x2.add_(x1) # 텐서의 메모리에 직접 적용되는 내부연산, 내부연산은 일반적으로 함수명에 _을 붙여준다
print("x2 add to x1:",'\n', x2) # x2를 호출해도 x1과 합쳐지기 전이 아닌 합쳐진 x2가 출력된다는걸 말하고 싶었나 봄


x1: tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
x2: tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])

x2 add to x1: 
 tensor([[1.1360, 1.1952, 1.0107],
        [0.8708, 1.1824, 1.4056]])


In [12]:
x = torch.arange(6)
print("x:", x)

x = x.view(2,3) # 2행 3열로
print("x:", x)

x = x.permute(1,0) # transpose
print("x", x)

x: tensor([0, 1, 2, 3, 4, 5])
x: tensor([[0, 1, 2],
        [3, 4, 5]])
x tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [13]:
x = torch.arange(6)
x = x.view(2,3)
print("X", x)

W = torch.arange(9).view(3, 3)
print("W", W)

h = torch.matmul(x,W) # 행렬 곱
print("h", h)


X tensor([[0, 1, 2],
        [3, 4, 5]])
W tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
h tensor([[15, 18, 21],
        [42, 54, 66]])


In [14]:
x = torch.arange(12).view(3,4)
print("X", x)
print(x[:, 1]) # 각 행의 1번째 요소
print(x[0]) # 0번째 행
print(x[:2, -1]) # 0~1까지 행에서 마지막 요소
print(x[1:3, :]) # 1~2까지 행에서 처음부터 끝까지 

X tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([1, 5, 9])
tensor([0, 1, 2, 3])
tensor([3, 7])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


pytorch는 우리가 정의한 함수의 기울기/도함수를 자동으로 계산해 줄 수 있다
-> 왜 이게 필요한가? -> 우리가 어떤 것을 예측할 때 딥러닝을 사용 -> 어? 그런데 예측값이 실제랑 너무 차이나네...-> 문제는 가중치가 잘못 설정 된거 -> 그러면 가중치를 어떻게 잘 맞출 수 있을까? ->바로 그래디언트(다변수 함수의 편미분 벡터, 즉 함수의 값이 가장 빠르게 증가하는 방향!) (그냥 다변수 함수에서의 기울기라 생각) -> 기울기는 왜? -> 실제 값과 예측값의 차를 그래프로 그린 후 그 최소점을 가중치로 설정할건데 그 때 기울기가 0이 되는 부분이 최소점이 되는거임-> 근데 극소값이 없는 그래프는? -> 그러면 기울기가 가장크게 증가 또는 감소 하는 방향을 찾아서 그나마 제일 작은 값을 가중치로 쓰는거지 뭐 어쩌겠으

In [15]:
x = torch.ones((3,))
print(x.requires_grad) # gradient 필요한지


False


In [16]:
x.requires_grad_(True) # 그래디언트 필요하다고 
print(x.requires_grad)

True


In [17]:
x = torch.arange(3, dtype=torch.float32, requires_grad=True) # 0~3까지 ,실수형으로 그래디언트 사용할 수 있게 만들어
print("x:", x)

x: tensor([0., 1., 2.], requires_grad=True)


In [24]:
a = x + 2
print("a",a)
b = a**2
print("b",b)
c = b + 3
print("c",c)
y = c.mean() # 각 요소들을 더하고 요소의 수만큼 나눔 
print("Y", y)
y.backward()  
# y에 대한 역전파(backpropagation)를 수행하며 y에 대한 gredient를 계산
# 이 값에 따라 .requires_grad(True)를 호출한 텐서 x의 그래디언트도 계산되어 x.grad에 저장
# .backward() 함수는 스칼라 출력에 대해서만 자동으로 그래디언트를 계산할 수 있다.
print(x.grad)



a tensor([2., 3., 4.], grad_fn=<AddBackward0>)
b tensor([ 4.,  9., 16.], grad_fn=<PowBackward0>)
c tensor([ 7., 12., 19.], grad_fn=<AddBackward0>)
Y tensor(12.6667, grad_fn=<MeanBackward0>)
tensor([4., 6., 8.])
None


/tmp/ipykernel_2393/1544413661.py:13: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:486.)
  print(a.grad)
